asset/urls.py
from django.urls import path

from .views import (
    AssetCreateView,
    AssetDetailView,
    AssetUpdateView,
    SubjectAutocomplete,
    PlaceAutocomplete,
    AssetAPI,
    )

app_name = 'asset'

urlpatterns = [
    path('detail/<int:pk>/', AssetDetailView.as_view(), name='detail-asset'),
    path('add/', AssetCreateView.as_view(), name='add-asset'),
    path('edit/<int:pk>/', AssetUpdateView.as_view(), name='update-asset'),
    path('api/subject-autocomplete', SubjectAutocomplete.as_view(), name='get-subject-tags'),
    path('api/place-autocomplete', PlaceAutocomplete.as_view(), name='get-place-tags'),
    path('api/asset', AssetAPI.as_view({'get':'list'}), name='api-asset'),
    path('api/detail/<int:pk>/', AssetAPI.as_view({'get': 'retrieve'}), name='api-detail'),
]

asset/forms.py
from django import forms
from django.urls import reverse_lazy
from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, ButtonHolder, Submit, Reset, Button, HTML
from crispy_forms.bootstrap import AppendedText

from .models import Asset, Organization

class AssetCreateForm(forms.ModelForm):
    """
    Form for the creation or update a new data asset
    """
    parent = forms.ModelChoiceField(queryset=Asset.objects.filter(parent=None),
                                    required=False,
                                    empty_label='Select the parent asset, if applicable.')

    def __init__(self, *args, **kwargs):
        super(AssetCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form'
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Div(
                Div('name', css_class= 'form-group col-md-10'),            
                Div('subject_tags', css_class= 'form-group col-md-10'),
                Div('status', css_class= 'form-group col-md-4'),
                Div('description', css_class= 'form-group col-md-10'),
                Div('isContracted', css_class= 'form-group col-md-12'),
                Div('spatial_scale', css_class= 'form-group col-md-4'),
                css_class= 'form-row'
            ),
            Div(
                Div('start_month', css_class= 'form-group col-md-2'),
                Div('end_month', css_class= 'form-group col-md-2 offset-md-1'),
                css_class = 'form-row'
            ),
            Div(
                Div('start_year', css_class= 'form-group col-md-2'),
                Div('end_year', css_class= 'form-group col-md-2 offset-md-1'),
                Div('place_tags', css_class= 'form-group col-md-10'),
                css_class= 'form-row',
            ),
            Div(
                Div('organization', css_class='form-group col-md-7'),
                Div('primary_contact_name', css_class='form-group col-md-7'),
                css_class = 'form-row',
            ),
            Div(
                Div('primary_contact_email', css_class= 'form-group col-md-4'),
                Div('primary_contact_phone', css_class= 'form-group col-md-3'),
                Div('primary_contact_phone_ext', css_class= 'form-group col-md-1'),
                Div('primary_contact_address1', css_class= 'form-group col-md-8'),
                Div('primary_contact_address2', css_class= 'form-group col-md-8'),
                css_class= 'form-row'
            ),
            Div(
                Div('primary_contact_city', css_class= 'form-group col-md-5'),
                Div('primary_contact_state', css_class= 'form-group col-md-2'),
                Div('primary_contact_zip', css_class = 'form-group col-md-1'),
                css_class = 'form-row'
            ),
            HTML("<div class='my-5'></div>"),
            Div(Div(
                HTML('<input id="copy_contact_info" name="copy_contact" style="margin-right: 10px;"'
                     'type="checkbox" onchange="copyContactHandler(this)">'),
                HTML('<label for="copy_contact_info">Contact for data is the same as primary contact</label>')),
                css_class = 'form-row',
                ),
            Div(
                Div('data_contact_name', css_class='form-grouo col-md-7'),
                css_class= 'form-row'
            ),
            Div(
                Div('data_contact_email', css_class= 'form-group col-md-4'),
                Div('data_contact_phone', css_class= 'form-group col-md-3'),
                Div('data_contact_phone_ext', css_class= 'form-group col-md-1'),
                css_class= 'form-row'
            ),
            Div(
                Div('data_contact_address1', css_class= 'form-group col-md-8'),
                Div('data_contact_address2', css_class= 'form-group col-md-8'),
                css_class= 'form-row'
            ),
            Div(
                Div('data_contact_city', css_class= 'form-group col-md-5'),
                Div('data_contact_state', css_class= 'form-group col-md-2'),
                Div('data_contact_zip', css_class = 'form-group col-md-1'),
                css_class= 'form-row'
            ),
            Div(
                Div('partners', css_class= 'form-group col-md-10'),
                css_class= 'form-row'
            ),
            ButtonHolder(
                Submit('submit', 'Save', css_class='btn btn-primary')
                )
            )

    class Meta:
        model = Asset
        fields = '__all__'
        widgets = {
            'subject_tags':
                autocomplete.TaggitSelect2(url='asset:get-subject-tags',
                    attrs={'class':'form-control'},
                ),
            'place_tags':
                autocomplete.TaggitSelect2(url='asset:get-place-tags',
                    attrs={'class':'form-control'},
                ),
            'primary_contact_address2':
                forms.TextInput(attrs={'placeholder': 'Building, Suite, Floor, Mailstop'},
                ),
            'data_contact_address2':
                forms.TextInput(attrs={'placeholder': 'Building, Suite, Floor, Mailstop'},
                ),
            'primary_contact_email':
                forms.TextInput(attrs={'placeholder': 'john_simth@fws.gov'},
                ),
            'primary_contact_phone':
                forms.TextInput(attrs={'placeholder': '(123) 222-4545'},
                ),
            'data_contact_phone':
                forms.TextInput(attrs={'placeholder': '(123) 222-4545'},
                ),
        }

asset/views.py
from django.db.models.query import Prefetch
from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.core.mail import mail_admins
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.template.loader import render_to_string
from rest_framework import generics, viewsets
from django_tables2 import RequestConfig, SingleTableMixin
from django_filters.views import FilterView
from dal import autocomplete

from .models import Asset, TaggedSubject, TaggedPlace, SubjectTag, LocationTag
from .forms import AssetCreateForm
from .filters import AssetFilter
from .serializers import AssetSerializer


class AssetCreateView(SuccessMessageMixin, CreateView):
    """ """
    model = Asset
    template_name = 'asset_create.html'
    form_class = AssetCreateForm
    success_url = reverse_lazy('asset-table-listing')
    success_message = "%(name)s was created successfully"

    def form_valid(self, form):
        """ Send an email to admins notifying them that a new asset has been created, for review. """
        msg = render_to_string('asset_create_email.txt',
            {
            'name': form.cleaned_data.get('name'),
            'organization': form.cleaned_data.get('organization'),
            'description': form.cleaned_data.get('description'),
            'primary_contact_name': form.cleaned_data.get('primary_contact_name'),
            'primary_contact_email': form.cleaned_data.get('primary_contact_email')
            })
        mail_admins(subject="New asset added", message=msg)

        return super(AssetCreateView, self).form_valid(form)


class AssetUpdateView(UpdateView):
    """ """
    model = Asset
    template_name = 'asset_create.html'
    form_class = AssetCreateForm
    #success_message = ""
    success_url = reverse_lazy('asset-table-listing')


class AssetDetailView(DetailView):
    """
    Display non-editable details for asset object.
    """
    model = Asset
    context_object_name = 'asset'
    template_name = 'asset_detail.html'

    def get_object(self):
        return Asset.objects.prefetch_related(Prefetch('child_asset', to_attr="sub_assets")).get(pk=self.kwargs['pk'])


# Views for API calls below
class SubjectAutocomplete(autocomplete.Select2QuerySetView):
    """
    API view to return subject tags for autocomplete.
    """
    def has_add_permission(self, request):
        """
        Override the default to require a user to be authenticated in order to add tags.
        This may turn out to be a bad idea if abused by users.
        """
        return True

    def get_queryset(self):
        qs = SubjectTag.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class PlaceAutocomplete(autocomplete.Select2QuerySetView):
    """
    API view to retun place tags for autocomplete
    """
    def has_add_permission(self, request):
        """
        Override the default to require a user to be authenticated in order to add tags.
        This may turn out to be a bad idea if abused by users.
        """
        return True

    def get_queryset(self):
        qs = LocationTag.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class AssetAPI(viewsets.ReadOnlyModelViewSet):
    """
    A basic viewset for viewing assets.
    """
    queryset = Asset.objects.all()
    serializer_class = AssetSerializer

asset/templates/About.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="active"><span>About</span></li>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
  <h1>Catalog Description</h1>

<p>The Migratory Bird Program's Strategic Plan: 2018-28 includes "Manage Bird Data and Information" as one of the Program’s four primary goals. The first objective under this goal is to modernize our data management processes and establish a data governance structure.</p>

<p>A necessary step to meet this strategic goal will be the development of a comprehensive accounting of our data resources and assessment of our data management capacity and needs. To aid this effort, the Migratory Bird Program (MBP) is developing a data catalog. The catalog is based on a preliminary data asset inventory that was compiled by the Migratory Bird Data Management Team through a program-wide survey. There are three primary purposes for this catalog:</p>

<ol>
<li>To assist the Migratory Bird Program in planning, prioritizing, and supporting our data management activities, and communicating about our data resources;</li>
<li>To provide a coherent structure for data management and data governance; and,</li>
<li>To improve data discoverability, access, and integration.</li>
</ol>

<p>When fully operational, the catalog will provide a <b>list of data assets for which the MBP has primary responsibility</b>, along with searchable metadata that is compatible with ServCat, USGS, and Data.gov metadata schemas.</p>

<p><b><i>What is a Migratory Bird Program data asset?</i></b> For the purposes of creating a catalog, we have established the following definitions and rules:</p>

  <p><b>Data Asset</b>: A collection of data and data elements that are organized and managed as a single entity and that inform specific decisions or identifiable products. Data elements within a data asset may include: data tables with original measurements, estimates, or model predictions, shapefiles, specialized software & platforms, documents, and code.</p>

<p>A data asset will be included in the catalog if the MBP <b>maintains and stores the unique or definitive version of the data</b> (<i>aka</i>, the authoritative version).  Data that are available from other USFWS programs or external partners will not be included, unless data from these sources have been edited or manipulated in a non-reproducible manner and are essential for MBP operations or decisions.  Included in the catalog are data assets that MBP contracts with others to maintain, under the presumption that the MBP will  assume maintenance of the asset upon termination of the contract.</p>

<p>Data assets that are logically, logistically, or programmatically associated with one another are associated with the same Migratory Bird Data Project. Assets within a MigBird Data Project share a common history, administration, decision context, and/or species+location+platform.</p>

<p>Coordinating the management of related data assets is necessary for (i) effective data discoverability and integration (catalog goal #3), (ii) extending the usefulness of historical data, and (iii) ensuring the preservation of small-scale datasets. Identifying the governing project will enable efficient data governance and prioritization, and improve programmatic planning, resource allocation, and communication (catalog goals #1 and #2). Once a Programmatic governance structure is in place, a process for establishing appropriate relationships among data assets should be established.</p>
</div>
{% endblock content %}

asset/templates/asset_catalog.html
{% extends "base.html" %}

{% block content %}

{% if asset_list %}
<div class="">
  <span class="">Name:</span> {{ asset.name }}
  <span class="">Stewardship Organization:</span> {{ asset.stewardship_organization }}
  <span class="">Description:</span> {{ asset.description }}

  <div class="">
    <span class="">Time-span</span>
    <span class="">Scale</span>
  </div>

  <div class="">
    <span class="">Tags</span> {{ for tags in asset.tags ?}}
  </div>
</div>

{% else %}
  <p> There are no assets </p>
{% endif %}

{% endblock content %}

asset/templates/asset_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block breadcrumb %}
  <li class="active"><span>
      {% if object %}
        Update
      {% else %}
        Add
      {% endif %}
    </span></li>
{% endblock breadcrumb %}

{% block content %}
  <div class="container">
    {% crispy form %}
  </div>
{% endblock content %}

{% block javascript %}
<link href="{% static 'autocomplete_light/vendor/select2/dist/css/select2.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'autocomplete_light/select2.css' %}" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/vendor/select2/dist/js/select2.full.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
{% endblock javascript %}

asset/templates/asset_datatable.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/b-1.5.1/fh-3.1.3/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/b-1.5.1/fh-3.1.3/datatables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script type="text/javascript" defer src="static/js/datatable.js"></script>

{% endblock header %}

{% block content %}
  <div class="container">
    <table id="asset_table" class="stripe row-border"></table>
  </div>
{% endblock content %}

asset/templates/asset_detail.html
{% extends "base.html" %}

{% block header %}
{% endblock header %}

{% block breadcrumb %}
  <li class="active"><span>Detail</span></li>
{% endblock breadcrumb %}

{% block content %}


  <div class="container">
    <div class="row border-bottom">
      <h1 id='asset-title'>{{ asset.name }}</h1>
    </div>

    <div id="button-block" class="d-flex justify-content-end">
            <a href= "{% url 'asset:update-asset' pk=asset.pk %}" alt="Edit asset" id="edit-button" class="btn btn-sm btn-outline-primary"
            style="margin-right:5px;">
                <i class="fas fa-pencil-alt"></i> Edit</a>
            <span class='disable-links'>
              <a href="javascript:window.print()" alt="Print page" id="print-button" class="btn btn-sm btn-outline-primary">
                <i class="fas fa-print"></i> Print</a>
            </span>
    </div>

  </div>
  <div class="container">
    <div class="row row-grid">
        <div class="col-3"><h6>Stewardship Organization</h6></div>
        <div class="col-9">{{ asset.organization }}</div>
    </div>
    {% if asset.partners %}
    <div class="row row-grid">
      <div class="col-3"><h6>Partners</h6></div>
      <div class="col-9">{{ asset.partners }}</div>
    </div>
    {% endif %}
    <div class="row row-grid">
        <div class="col-3"><h6>Storage or maintenance contracted</h6></div>
        <div class="col-9">{{ asset.isContracted|yesno:"Yes,No" }}</div>
    </div>
    <div class="row row-grid">
        <div class="col-3"><h6>Status</h6></div>
        <div class="col-9">{{ asset.status }}</div>
    </div>
    <div class="row row-grid">
        <div class="col-3"><h6>Spatial scale</h6></div>
        <div class="col-9">{{ asset.spatial_scale }}</div>
    </div>
    <div class="row row-grid">
        <div class="col-3"><h6>Abstract</h6></div>
        <div class="col-9">{{ asset.description }}</div>
    </div>
    <div class="row row-grid">
        <div class="col-3"><h6>Keywords</h6></div>
        <div class="col-9">
              {{ asset.subject_taglist }}
        </div>
    </div>
    <div class="row row-grid">
        <div class="col-3"><h6>Collection Period</h6></div>
        <div class="col-9"> {{ asset.start_month}} - {{ asset.end_month}}</div>
    </div>
    <div class="row row-grid">
          <div class="col-3"><h6>Asset time span</h6></div>
          <div class="col-9"> {{asset.start_year}} - {{ asset.end_year }}</div>
    </div>

    <div class="row row-grid">
      <div class="col-3"><h6>Primary Contact</h6></div>
      <div class="col-9">
          {{ asset.primary_contact_name }}<br>
          {{ asset.primary_contact_address1 }}<br>
          {% if asset.primary_contact_address2 %}
            {{ asset.primary_contact_address2 }}<br>
          {% endif %}
          {{ asset.primary_contact_city}} {{ asset.primary_contact_state }} {{asset.primary_contact_zip}}
          <br>
          {{ asset.primary_contact_phone }}<br>
          {{ asset.primary_contact_email}}
        </div>
      </div>

    <div class="row row-grid">
      <div class="col-3"><h6>Data Contact</h6></div>
      <div class="col-9">
        {{ asset.data_contact_name }}<br>
        {{ asset.data_contact_address1 }}<br>
        {% if asset.data_contact_address2 %}
          {{ asset.data_contact_address2 }}<br>
        {% endif %}
        {{ asset.data_contact_city}} {{ asset.data_contact_state }} {{asset.data_contact_zip}}
        <br>
        {{ asset.data_contact_phone }}<br>
        {{ asset.data_contact_email}}
      </div>
    </div>

    <div class="row row-grid">
      <div class="col-3"><h6>Location keywords</h6></div>
      <div class="col-9">{{ asset.place_taglist }}</div>
    </div>


    <div class="float-right font-italic small" style="padding-top: 75px;">
      Last updated: {{ asset.last_modified |date:"F j, Y" }}
    </div>

</div>
{% endblock content %}